### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by NehemiahAT**
The JS still says `helloH` as the ID for the "Hello!" text, while the HTML says `HelloH`.

Was this because of the conflict and can we change the ID?

I am trying to fix the HTML because `HelloH` goes against the capitalization standards.

### CODE REVIEW

**Comment by NehemiahAT** [comment]
Thanks for merging my previous PRs.

**Comment by DrBeta** [comment]
Your welcome. Software is always better with someone else, but you still need to change `main.js`

**Comment by DrBeta** [comment]
And it also works now. I had fixed it

**Comment by NehemiahAT** [comment]
What do I need to do?

**Comment by NehemiahAT** [comment]
Thanks for fixing it. Shall we call this 1.02?

**Comment by DrBeta** [comment]
Already changed it to 1.0.2

**Pull request closed without merging**
